# https://elk-docker.readthedocs.io/
# https://docs.mongodb.com/manual/reference/default-mongodb-port/
# https://github.com/mongo-express/docker-official-images
version: '3.1'

services:
  mongo:
    image: mongo
    #    restart: always
    network_mode: "host"
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: candygramformongo
      MONGO_INITDB_ROOT_PASSWORD: 874eavNDFKJDSt5eo8m4w
    volumes:
      - ./db/data/:/db/data/
  mongo-express:
    image: mongo-express
    #    restart: always
    network_mode: "host"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: candygramformongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: 874eavNDFKJDSt5eo8m4w
    volumes:
      - ./db/data/:/db/data/
